### ISSUE TITLE
Lab0 will not start in Rstudio

### ISSUE THREAD

**Issue by ncooper76** [jbryer/DATA606Fall2017#1]
Hello;

I tried starting Lab0 the R commands I used are below:
> getLabs()
 [1] "Lab0"  "Lab1"  "Lab2"  "Lab3"  "Lab4a" "Lab4b"
 [7] "Lab5"  "Lab6"  "Lab7"  "Lab8" 
> startLab('Lab0')
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
> startLab('Lab0') 
Error in startLab("Lab0") : 
  The lab did not copy! Not sure why, ask your instructor.
> library('DATA606')
> startLab('Lab0') 
Error in startLab("Lab0") : 
  The lab did not copy! Not sure why, ask your instructor.
> vignette(package='DATA606')
no vignettes found
> vignette('os3')
Warning message:
vignette ‘os3’ not found 

I went through and tried loading all the libraries one by one:

> library("DATA606", lib.loc="~/R/win-library/3.4")
> library("openintro", lib.loc="~/R/win-library/3.4")
Please visit openintro.org for free statistics
materials

Attaching package: ‘openintro’

The following object is masked from ‘package:datasets’:

    cars

Warning message:
package ‘openintro’ was built under R version 3.4.1 
> library("OIdata", lib.loc="~/R/win-library/3.4")
Loading required package: RCurl
Loading required package: bitops
Loading required package: maps
Warning messages:
1: package ‘OIdata’ was built under R version 3.4.1 
2: package ‘maps’ was built under R version 3.4.1 
> library("devtools", lib.loc="~/R/win-library/3.4")
Warning message:
package ‘devtools’ was built under R version 3.4.1 
> library("ggplot2", lib.loc="~/R/win-library/3.4")
Warning message:
package ‘ggplot2’ was built under R version 3.4.1 
> library("psych", lib.loc="~/R/win-library/3.4")

Attaching package: ‘psych’

The following objects are masked from ‘package:ggplot2’:

    %+%, alpha

Warning message:
package ‘psych’ was built under R version 3.4.1 
> library("reshape2", lib.loc="~/R/win-library/3.4")

Attaching package: ‘reshape2’

The following object is masked from ‘package:openintro’:

    tips

Warning message:
package ‘reshape2’ was built under R version 3.4.1 
> library("knitr", lib.loc="~/R/win-library/3.4")
Warning message:
package ‘knitr’ was built under R version 3.4.1 
> library("markdown", lib.loc="~/R/win-library/3.4")
Warning message:
package ‘markdown’ was built under R version 3.4.1 
> library("shiny", lib.loc="~/R/win-library/3.4")
Warning message:
package ‘shiny’ was built under R version 3.4.1 
> vignette('os3')
Warning message:
vignette ‘os3’ not found 
> startLab('Lab0') 
Error in startLab("Lab0") : 
  The lab did not copy! Not sure why, ask your instructor.

What did I do wrong?

Thanks,

Nathan

**Comment by mjdacs** [comment]
I am having similar problems:
> viewLab("Lab0")
''C:/Users/Mike' not found
'James/Anaconda3/R/library/DATA606/Labs/Lab0/intro_to_r.html'' not found
Warning message:
running command 'open 'C:/Users/Mike James/Anaconda3/R/library/DATA606/Labs/Lab0/intro_to_r.html'' had status 34 

and

 startLab('Lab0')
Error in startLab("Lab0") : 
  The lab did not copy! Not sure why, ask your instructor.

**Comment by mjdacs** [comment]
it does look like the lab did copy into my working directory, however. are you familiar with setting a working directory in rstudio?

**Comment by jbryer** [comment]
I made an update to the DATA606 that I hope fixes this issue. It seems to be isolated to certain Windows installations. For those that care, the `file.copy` command returns `FALSE` even though the copy occurred correctly. I check for the file in a different way now.

Also, be sure to see this post that includes some information about working directories: http://data606.net/post/2017-08-25-getting-started-with-r/
