### ISSUE TITLE
HW1 Q1.70

### ISSUE THREAD

**Issue by rafaldecowski** [jbryer/DATA606Fall2017#12]
Hello Professor,

Could you please elaborate on the simulation part of Q1.70?
My understanding is that running it 100 times helps to determine if the result variation is by chance. But how do we run such simulation in R? Which variables do we randomize? 

I submitted my HW with a couple of unanswered questions and would love to fully understand it and correct my assignment.

Any feedback would be helpful.

**Comment by jbryer** [comment]
This is a precursor to something called bootstrapping that we will discuss
in a few weeks. I'll show some R code during tonight's Meetup on how to do
it.
