### ISSUE TITLE
Lab 3

### ISSUE THREAD

**Issue by milkcake81** [jbryer/DATA606Fall2017#13]
In "try your own section", it says "Note that normal probability plots C and D have a slight stepwise pattern."

To me, it looks like plot C doesn't look skewed nor do I see stepwise pattern.  How do I detect stepwise pattern?

**Comment by jbryer** [comment]
Here is the normal QQ plot for age:
![image](https://user-images.githubusercontent.com/623759/30441852-9b40f2b6-9948-11e7-87df-eddfdf9cb1e3.png)

```
qqnorm(bdims$age)
qqline(bdims$age)
```

See the red lines I drew, the stepwise is that the points move across horizontally, then jump up to what looks to be another horizontal line. That is what is meant by stepwise. Why does this happen?

**Comment by milkcake81** [comment]
The one you just drew looks like Plot D.  It's probably caused by the fact that the survey is geared towards "young age adult" so you end up with more people who are young than not.  

My issue was with Plot C.  Let me try to paste the graph here if it works.  This looks normal to me.  
![capture](https://user-images.githubusercontent.com/16724936/30461253-06f04470-998b-11e7-94a0-526bc706f496.PNG)

**Comment by jbryer** [comment]
Sorry for the delay in responding @milkcake81. I think your conclusion that the data seems to be normal, but the question is about the apparent "stepping" of the data. Why is that? Think about the differences between, say, integers and real numbers and hopefully that will help explain the stepping.
