### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by doradu8030** [jbryer/DATA606Fall2017#14]
Good evening Jason, 

I might missed a piece of information when you were mentioning on the meetup, the new schedule for the following weeks. I just wanted to confirm the due date for this week homework(chap 3) and Lab3 would be Sept 20, correct ?

Thank you 
Durley Torres

**Comment by jbryer** [comment]
The schedule on this page is accurate: http://data606.net/course-overview/schedule/
Lab and homework for chapter 3 is due October 1st.

**Comment by doradu8030** [comment]
Hi Jason 
If I understood correctly, there is not homework neither Lab due until Oct 1st?
Thank you
Durley Torres


Sent on my Boost Mobile Samsung Galaxy S® 6
-------- Original message --------From: Jason Bryer <notifications@github.com> Date: 9/14/17  12:25 PM  (GMT-05:00) To: jbryer/DATA606Fall2017 <DATA606Fall2017@noreply.github.com> Cc: doradu8030 <durleytorresm@yahoo.com>, State change <state_change@noreply.github.com> Subject: Re: [jbryer/DATA606Fall2017] General Question (#14) 
The schedule on this page is accurate: http://data606.net/course-overview/schedule/

Lab and homework for chapter 3 is due October 1st.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jbryer/DATA606Fall2017","title":"jbryer/DATA606Fall2017","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jbryer/DATA606Fall2017"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbryer in #14: The schedule on this page is accurate: http://data606.net/course-overview/schedule/\r\nLab and homework for chapter 3 is due October 1st."}],"action":{"name":"View Issue","url":"https://github.com/jbryer/DATA606Fall2017/issues/14#issuecomment-329535757"}}}

**Comment by jbryer** [comment]
Chapter 2 homework and lab is due this Sunday, the October 1st for chapter
3.

**Comment by doradu8030** [comment]
I got it . I was a bit confused with the due dates I already submitted chap 2 lab and HW.  
Thank you for the clarification
Thank you
Durley 


Sent on my Boost Mobile Samsung Galaxy S® 6
-------- Original message --------From: Jason Bryer <notifications@github.com> Date: 9/14/17  2:01 PM  (GMT-05:00) To: jbryer/DATA606Fall2017 <DATA606Fall2017@noreply.github.com> Cc: doradu8030 <durleytorresm@yahoo.com>, State change <state_change@noreply.github.com> Subject: Re: [jbryer/DATA606Fall2017] General Question (#14) 
Chapter 2 homework and lab is due this Sunday, the October 1st for chapter

3.



On Thu, Sep 14, 2017 at 1:38 PM, doradu8030 <notifications@github.com>

wrote:
