### ISSUE TITLE
Lab 3

### ISSUE THREAD

**Issue by LilesB** [jbryer/DATA606Fall2017#15]
Good afternoon,

I recently uploaded the  lab for week 3, can you please look at it to see if the format is acceptable. I come from a background with SAS so R and R Studio is very new to me.

Thanks in advance

**Comment by jbryer** [comment]
Can you email me your Lab 3? I will not look at chapter 3 work (homework or labs) until after October 1st. It also very helpful if you ask more specific questions related to labs.
