### ISSUE TITLE
Due date for assignments

### ISSUE THREAD

**Issue by kmehdi2017** [jbryer/DATA606Fall2017#16]
I am a bit confused about the due dates of assignments. As per the schedule in data606.net today (09/17) we should be submitting Lab2 and Homework 2 (which I submitted last week). I just submitted Lab3 today and working on homework 3 - but it seems the due date is on October 01 (10/01). Am I missing anything here? - Mehdi

**Comment by jbryer** [comment]
The due dates on this page are accurate: http://data606.net/course-overview/schedule/
I will update Blackboard soon.
