### ISSUE TITLE
Observation Independent or Not Based on Sample Size

### ISSUE THREAD

**Issue by Tyllis** [jbryer/DATA606Fall2017#19]
In Chapter 4 - Inference, I frequently encountered this statement:

"Because this is a simple random sample from less than 10% of the population, the observation are independent."

On Pg 173 of the text, it states, "A reliable method to ensure sample observations are independent is to conduct a simple random sample consisting of less than 10% of the population."

I wonder why this is so. 

Does that mean that if I sample more than 10% of the population, the observation becomes non-independent?

**Comment by jbryer** [comment]
Good question. I will discuss this in detail at the next Meetup. In the
meantime, here is a thorough explanation:
https://www.ma.utexas.edu/users/mks/M358KInstr/TenPctCond.pdf

In short, sampling without replacement technically creates
non-independence.  Consider a population of 10, the probability of picking
person A (or anyone really) is 1/10. Once I pick a person, the probability
of picking person A on round two is now 1/9. Therefore, knowing the result
of the first pick changes the probability of the second pick. With 10
people this changes the probability by 10% after the first pick.

Now consider a population of 1,000. The probability of picking person A on
round one is 1/1,000, for round two it 1/999. Much smaller change in the
probability. The 10% rule (which is arbitrary by the way) is simply saying
that as long as you sample less than 10% of the population, the samples
are, more-or-less, independent.

**Comment by Tyllis** [comment]
I see. This is related to sampling without replacement. That explains it.

I found a similar explanation in the textbook, Chap 2.3, Pg 103.

Thanks!
