### ISSUE TITLE
The R files in Lab0 do not contain any code/data

### ISSUE THREAD

**Issue by mjdacs** [jbryer/DATA606Fall2017#2]
Hi,

When I try to open 'arbuhnot' and 'present' in the Lab0/more folder, it pops open a new tab in Rstudio but is a blank page. Is this expected?

update: I did source("more/arbuthnot.R") from the working directory and obtained the data set...

Thanks,
Mike

**Comment by jbryer** [comment]
Hi Mike. Is this working for you now?

**Comment by mjdacs** [comment]
Yes it is, thank you!
