### ISSUE TITLE
Lab 5 error

### ISSUE THREAD

**Issue by swigodsky** [jbryer/DATA606Fall2017#22]
I get an error when I use the following code that was embedded in lab 5 in question 4:

inference(y = nc$weight, x = nc$habit, est = "mean", type = "ht", null = 0, 
          alternative = "twosided", method = "theoretical")

The error I get is:
Error in FUN(dd[x, ], ...) : could not find function "FUN"

Before the error, I do get the following result- 
Summary statistics:
n_nonsmoker = 873, mean_nonsmoker = 7.1443,
I thought I would get statistics for smokers also.  
Please let me know how to fix this.
Thanks,
Sarah

**Comment by ntlrs** [comment]
I'm having the same error! Any chance you got it figured out?

**Comment by swigodsky** [comment]
Yes.  I got help with it during the meet up.  Apparently I had another variable stored with the same name.  I needed to clear my history.  You can do that by going I into the session tab at the top of the page.  You may also need to restart R.  Also, even though I couldn’t run the script, it knit properly.  I hope this helps.
Sarah

**Comment by jbryer** [comment]
See the end of the October 25th meetup for the solution.
