### ISSUE TITLE
Rmarkdown did not save or knit correctly

### ISSUE THREAD

**Issue by mjdacs** [jbryer/DATA606Fall2017#4]
I was answering the questions in Lab0 and the Rmarkdown would not update as I knitted. Frustrated, I saved the script as an .Rmd file and moved on. When I tried to reopen the .Rmd file again in Rstudio, the page is blank except for an output and a plot, which are in reverse order. It appears I lost everything.

I created a test file Rmd and the first knit to PDF works. But its the only knit that works. And if I close that .Rmd file and try to reopen it again, it too is a blank page.

I am running win10, Rstudio v1.0.136, and R v3.4.1.

**Comment by jbryer** [comment]
This is very strange indeed. Just to confirm, you created a new Rmd file from the Rstudio menu, saved that Rmd somewhere, then when you close and reopen Rstudio that Rmd file is blank? 

It looks like you not are running the latest version of Rstudio. Might be worth upgrading. I have been running the preview version for about a month without any issues which has some nice new features. You can get that at: https://www.rstudio.com/products/rstudio/download/preview/
If you are uncomfortable running preview or beta software, here is the main download page: https://www.rstudio.com/products/rstudio/download/

If this is keeps happening, shoot me an email so we can schedule a time to get on GoToMeeting.

**Comment by mjdacs** [comment]
I updated Rstudio to the preview. It looks like things are working again. Thanks a lot for your help!

**Comment by jbryer** [comment]
Great!
