### ISSUE TITLE
can't access abruthnot data

### ISSUE THREAD

**Issue by swigodsky** [jbryer/DATA606Fall2017#6]
Hi,
I opened lab 0 but when I type 

{r load-abrbuthnot-data, eval=TRUE}
source("more/arbuthnot.R")

at the prompt (or any variation of that), I get the following error

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'more/arbuthnot.R': No such file or directory

Please let me know how to address this.
Thanks,
Sarah

**Comment by swigodsky** [comment]
i figured it out

**Comment by doradu8030** [comment]
Hi Sara  
how did you resolve this issue? I have the same error trying to load Lab1
Could you please help? 

Thank you 

Durley

**Comment by jbryer** [comment]
This is usually related to not setting the working directory correctly. See
this page for more information:
http://data606.net/post/2017-08-25-getting-started-with-r/

**Comment by swigodsky** [comment]
Hi Durley,

I had a number of issues and so I'm going to do my best to remember how I resolved this- I think I needed to save the rmd file in the folder the computer had saved lab 1.  Then I needed to go into the screen on the bottom right in R and click on Files, click on More and click on Set as working directory.
Good luck and I hope this helps,
Sarah

**Comment by doradu8030** [comment]
Thank you Sarab for replying . I figured out and yes you are totally correct, it works perfectly. 
Thank you very much
Durley


Sent on my Boost Mobile Samsung Galaxy S® 6
-------- Original message --------From: swigodsky <notifications@github.com> Date: 9/5/17  9:57 PM  (GMT-05:00) To: jbryer/DATA606Fall2017 <DATA606Fall2017@noreply.github.com> Cc: doradu8030 <durleytorresm@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [jbryer/DATA606Fall2017] can't access abruthnot data (#6) 
Hi Durley,



I had a number of issues and so I'm going to do my best to remember how I resolved this- I think I needed to save the rmd file in the folder the computer had saved lab 1.  Then I needed to go into the screen on the bottom right in R and click on Files, click on More and click on Set as working directory.

Good luck and I hope this helps,

Sarah
