### ISSUE TITLE
Week 2 assignment?

### ISSUE THREAD

**Issue by milkcake81** [jbryer/DATA606Fall2017#7]
Hi,

Is it possible to post few weeks of assignments ahead?  I have a lot of ups and downs in my job so I would like to take a stab at it when I have time.

**Comment by jbryer** [comment]
All the assignments for the entire semester are listed here:
http://data606.net/assignments/ There is not problem with getting ahead if
you wish.

**Comment by milkcake81** [comment]
Ah sorry, wrong course! I meant to ask for this for Data 607.  Sorry about that.
