### ISSUE TITLE
Rmarkdowns not displaying Dataframe rows

### ISSUE THREAD

**Issue by nobieyi00** [jbryer/DATA606Fall2017#8]
Hi,

I am having an issue, with the Rmarkdowns for the labs, when I run the statement to display head(present) dataframe. I don't see it on the same page(markdown sheet). But if I run it directly at the console prompts I see the data.

See screen shot attached
![rmarkdown_df](https://user-images.githubusercontent.com/20451211/29988777-ff6146da-8f3c-11e7-994a-033d374b633e.PNG)

**Comment by nobieyi00** [comment]
so far

I am using the below to display the data in Rmarkdown 
knitr::kable(tail(cdc), format = "html")

**Comment by jbryer** [comment]
This is very strange. It looks like the table was partially rendered. I tend to prefer my output to display in the console. You can change the behavior of the Rmd output by clicking gear icon next the Knit button. Try choosing "Chunk Output in Console" and see if that works.

**Comment by nobieyi00** [comment]
It works thanks. Do you think it is because I am using R version 3.3?
